In [1]:
import sys
print(sys.executable)

c:\Users\srrikanth yadav\OneDrive\Desktop\Infosys_7.0\MedTrack_DV\venv312\Scripts\python.exe

### 1. Import Libraries

In [3]:
import pandas as pd
print(pd.__version__)

3.0.5

In [4]:
import numpy as np
print(np.__version__)

2.5.1

### 2. Load Dataset

In [6]:
import pandas as pd

df = pd.read_csv("../data/raw/hospital_raw_data.csv")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

Dataset loaded successfully!
Rows: 7634
Columns: 32

,Patient_ID,Admission_ID,Hospital_ID,Hospital_Name,Region,Department,Admission_Date,Discharge_Date,Admission_Type,Patient_Type,...,Total_Beds,Occupied_Beds,Available_Beds,Staff_Count,Doctor_Count,Nurse_Count,Equipment_Type,Equipment_Total,Equipment_In_Use,Treatment_Cost
0,PAT-21518,ADM-149984,HOSP-04,Apex Healthcare Center,West,Intensive Care,2023-05-11,2023-05-16,Urgent,Outpatient,...,500,301,199,600,110,380,MRI Scanner,16.0,6.0,17367.5
1,PAT-23509,ADM-132964,HOSP-03,City Care Hospital,East,Pediatrics,2023-02-15,2023-02-16,emergency,Inpatient,...,300,193,107,350,60,210,Ventilator,58.0,7.0,4800.0
2,PAT-12876,ADM-112443,HOSP-06,Cedar Sinai Community Hospital,North,Emergency,2023-10-15,2023-10-20,Urgent,Day Care,...,320,241,79,370,68,230,Patient Monitor,56.0,9.0,13688.0
3,PAT-37202,ADM-136750,HOSP-07,Oakridge Health Center,South,Cardiology,2023-04-04,2023-04-12,Elective,Outpatient,...,280,216,64,320,55,190,Patient Monitor,42.0,27.0,16396.0
4,PAT-19893,ADM-144098,HOSP-01,Metro General Hospital,North,ICU,2025-03-10,2025-04-01,Urgent,Inpatient,...,450,287,163,520,95,310,MRI Scanner,26.0,19.0,41290.0

### 3. Dataset Overview

In [7]:
df.head(5)

,Patient_ID,Admission_ID,Hospital_ID,Hospital_Name,Region,Department,Admission_Date,Discharge_Date,Admission_Type,Patient_Type,...,Total_Beds,Occupied_Beds,Available_Beds,Staff_Count,Doctor_Count,Nurse_Count,Equipment_Type,Equipment_Total,Equipment_In_Use,Treatment_Cost
0,PAT-21518,ADM-149984,HOSP-04,Apex Healthcare Center,West,Intensive Care,2023-05-11,2023-05-16,Urgent,Outpatient,...,500,301,199,600,110,380,MRI Scanner,16.0,6.0,17367.5
1,PAT-23509,ADM-132964,HOSP-03,City Care Hospital,East,Pediatrics,2023-02-15,2023-02-16,emergency,Inpatient,...,300,193,107,350,60,210,Ventilator,58.0,7.0,4800.0
2,PAT-12876,ADM-112443,HOSP-06,Cedar Sinai Community Hospital,North,Emergency,2023-10-15,2023-10-20,Urgent,Day Care,...,320,241,79,370,68,230,Patient Monitor,56.0,9.0,13688.0
3,PAT-37202,ADM-136750,HOSP-07,Oakridge Health Center,South,Cardiology,2023-04-04,2023-04-12,Elective,Outpatient,...,280,216,64,320,55,190,Patient Monitor,42.0,27.0,16396.0
4,PAT-19893,ADM-144098,HOSP-01,Metro General Hospital,North,ICU,2025-03-10,2025-04-01,Urgent,Inpatient,...,450,287,163,520,95,310,MRI Scanner,26.0,19.0,41290.0

### 4. Shape

In [ ]:
print(f'Dataset Shape: {df.shape[0]} rows, {df.shape[1]} columns')

### 5. Column Names

In [ ]:
print(list(df.columns))

### 6. Data Types

In [9]:
df.dtypes

Patient_ID              str
Admission_ID            str
Hospital_ID             str
Hospital_Name           str
Region                  str
Department              str
Admission_Date          str
Discharge_Date          str
Admission_Type          str
Patient_Type            str
Age                   int64
Gender                  str
Diagnosis               str
Treatment               str
Doctor_ID               str
Bed_ID                  str
Room_ID                 str
Length_of_Stay        int64
Readmitted              str
Readmission_Date        str
Admission_Source        str
Discharge_Status        str
Total_Beds            int64
Occupied_Beds         int64
Available_Beds        int64
Staff_Count           int64
Doctor_Count          int64
Nurse_Count           int64
Equipment_Type          str
Equipment_Total     float64
Equipment_In_Use    float64
Treatment_Cost      float64
dtype: object

### 7. Descriptive Statistics

In [ ]:
df.describe(include='all')

### 8. Missing Value Analysis

In [10]:
missing = df.isna().sum() + (df == '').sum()
missing_pct = (missing / len(df)) * 100
missing_df = pd.DataFrame({'Missing_Count': missing, 'Missing_Pct': missing_pct})
missing_df[missing_df['Missing_Count'] > 0]

                  Missing_Count  Missing_Pct
Treatment                   107     1.401624
Doctor_ID                   122     1.598114
Room_ID                      63     0.825255
Readmission_Date           6561    85.944459
Equipment_Type                1     0.013099
Equipment_Total               1     0.013099
Equipment_In_Use              1     0.013099
Treatment_Cost                1     0.013099

### 9. Duplicate Detection

In [11]:
dup_ids = df.duplicated(subset=['Admission_ID'], keep=False)
print(f'Total duplicate records based on Admission_ID: {dup_ids.sum()}')

Total duplicate records based on Admission_ID: 16

### 10. Duplicate Removal

In [12]:
initial_count = len(df)
df = df.drop_duplicates(subset=['Admission_ID'], keep='first').reset_index(drop=True)
print(f'Removed {initial_count - len(df)} duplicate records. New record count: {len(df)}')

Removed 8 duplicate records. New record count: 7626

### 11. Missing Value Treatment

In [ ]:
df['Treatment'] = df['Treatment'].replace('', np.nan).fillna('Standard Protocol')
df['Doctor_ID'] = df['Doctor_ID'].replace('', np.nan).fillna('DOC-999')
df['Room_ID'] = df['Room_ID'].replace('', np.nan).fillna('RM-100')

### 12. Department Name Standardization

In [ ]:
dept_clean_map = {
    'general medicine': 'General Medicine', 'gen med': 'General Medicine', 'general medicine ': 'General Medicine',
    'cardiology': 'Cardiology', 'cardiology ': 'Cardiology',
    'neurology': 'Neurology', 'neurology ': 'Neurology',
    'orthopedics': 'Orthopedics', 'orthopedics ': 'Orthopedics',
    'pediatrics': 'Pediatrics', 'pediatrics ': 'Pediatrics',
    'emergency': 'Emergency', 'emergency ': 'Emergency', 'er': 'Emergency',
    'icu': 'ICU', 'icu ': 'ICU', 'intensive care': 'ICU',
    'surgery': 'Surgery', 'surgery ': 'Surgery'
}
df['Department'] = df['Department'].str.strip().apply(
    lambda x: dept_clean_map.get(str(x).lower(), str(x).strip().title() if pd.notna(x) else 'General Medicine')
)
print('Standardized Departments:', sorted(df['Department'].unique()))

### 13. Hospital Name Standardization

In [ ]:
df['Hospital_Name'] = df['Hospital_Name'].str.strip()
print('Unique Standardized Hospitals:', df['Hospital_Name'].nunique())

### 14. Gender Standardization

In [ ]:
gender_map = {'m': 'Male', 'male': 'Male', 'f': 'Female', 'female': 'Female', 'other': 'Other'}
df['Gender'] = df['Gender'].str.strip().str.lower().map(lambda x: gender_map.get(x, 'Other'))
print('Gender Value Counts:\n', df['Gender'].value_counts())

### 15. Admission Type Standardization

In [ ]:
adm_type_map = {'emergency': 'Emergency', 'urgent': 'Urgent', 'elective': 'Elective'}
df['Admission_Type'] = df['Admission_Type'].str.strip().str.lower().map(lambda x: adm_type_map.get(x, 'Emergency'))
print('Admission Types:', df['Admission_Type'].unique())

### 16. Patient Type Standardization

In [ ]:
pat_type_map = {'inpatient': 'Inpatient', 'outpatient': 'Outpatient', 'emergency': 'Emergency', 'day care': 'Day Care'}
df['Patient_Type'] = df['Patient_Type'].str.strip().str.lower().map(lambda x: pat_type_map.get(x, 'Inpatient'))
print('Patient Types:', df['Patient_Type'].unique())

### 17. Date Conversion

In [ ]:
df['Admission_Date'] = pd.to_datetime(df['Admission_Date'], errors='coerce')
df['Discharge_Date'] = pd.to_datetime(df['Discharge_Date'], errors='coerce')
df['Readmission_Date'] = pd.to_datetime(df['Readmission_Date'], errors='coerce')

### 18. Invalid Date Detection

In [ ]:
invalid_dates = df[df['Discharge_Date'] < df['Admission_Date']]
print(f'Invalid date pairs (Discharge < Admission): {len(invalid_dates)}')
# Correcting invalid dates
df.loc[df['Discharge_Date'] < df['Admission_Date'], 'Discharge_Date'] = df['Admission_Date'] + pd.Timedelta(days=5)

### 19. Length of Stay Validation

In [ ]:
df['Length_of_Stay'] = (df['Discharge_Date'] - df['Admission_Date']).dt.days
df['Length_of_Stay'] = df['Length_of_Stay'].clip(lower=1)
print('Length of Stay Summary:')
print(df['Length_of_Stay'].describe())

### 20. Bed Capacity Validation

In [ ]:
df['Total_Beds'] = pd.to_numeric(df['Total_Beds'], errors='coerce').astype(int)
df['Occupied_Beds'] = pd.to_numeric(df['Occupied_Beds'], errors='coerce').astype(int)
# Cap Occupied_Beds to Total_Beds if overflow exists
df.loc[df['Occupied_Beds'] > df['Total_Beds'], 'Occupied_Beds'] = df['Total_Beds']
df['Available_Beds'] = df['Total_Beds'] - df['Occupied_Beds']
print('Bed capacity validation completed. Negative available beds count:', (df['Available_Beds'] < 0).sum())

### 21. Resource Data Validation

In [ ]:
for col in ['Staff_Count', 'Doctor_Count', 'Nurse_Count', 'Equipment_Total', 'Equipment_In_Use']:
    df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0).astype(int)
print('Resource Data Summary:')
df[['Staff_Count', 'Doctor_Count', 'Nurse_Count', 'Equipment_Total', 'Equipment_In_Use']].describe()

### 22. Numerical Range Validation

In [15]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
median_age = int(df['Age'][(df['Age'] >= 0) & (df['Age'] <= 110)].median())
df.loc[(df['Age'] < 0) | (df['Age'] > 110) | (df['Age'].isna()), 'Age'] = median_age
df['Age'] = df['Age'].astype(int)

df['Treatment_Cost'] = pd.to_numeric(df['Treatment_Cost'], errors='coerce').abs().round(2)
print('Age Range:', df['Age'].min(), 'to', df['Age'].max())
print('Treatment Cost Range: $', df['Treatment_Cost'].min(), 'to $', df['Treatment_Cost'].max())

Age Range: 0 to 95
Treatment Cost Range: $ 1105.0 to $ 122055.0

### 23. Outlier Detection

In [14]:
q1 = df['Treatment_Cost'].quantile(0.25)
q3 = df['Treatment_Cost'].quantile(0.75)
iqr = q3 - q1
high_cost_cases = df[df['Treatment_Cost'] > (q3 + 1.5 * iqr)]
print(f'Detected {len(high_cost_cases)} complex high-cost cases (retained as valid healthcare ICU/Surgical procedures).')

Detected 890 complex high-cost cases (retained as valid healthcare ICU/Surgical procedures).

### 24. Data Type Optimization

In [13]:
df['Admission_Date'] = df['Admission_Date'].dt.strftime('%Y-%m-%d')
df['Discharge_Date'] = df['Discharge_Date'].dt.strftime('%Y-%m-%d')
df['Readmission_Date'] = df['Readmission_Date'].dt.strftime('%Y-%m-%d').fillna('')
df.info()

AttributeError: Can only use .dt accessor with datetimelike values

### 25. Final Quality Validation

In [16]:
cleaned_records = len(df)
cleaned_cells = cleaned_records * len(df.columns)
missing_cells = sum(df[col].isin(['', np.nan]).sum() for col in df.columns if col != 'Readmission_Date')
completeness_pct = round(((cleaned_cells - missing_cells) / cleaned_cells) * 100, 2)
missing_pct = round((missing_cells / cleaned_cells) * 100, 2)

print('=' * 60)
print('FINAL CLEANED DATASET METRICS')
print('=' * 60)
print(f'Cleaned Record Count    : {cleaned_records:,}')
print(f'Dataset Completeness    : {completeness_pct}% (Target: > 95%)')
print(f'Missing Value Percentage: {missing_pct}% (Target: < 2%)')
print(f'Duplicates              : {df.duplicated(subset=["Admission_ID"]).sum()}')
print('=' * 60)
if completeness_pct > 95.0 and missing_pct < 2.0:
    print('MILESTONE 1 STATUS: PASSED')
else:
    print('MILESTONE 1 STATUS: FAILED')

============================================================
FINAL CLEANED DATASET METRICS
============================================================
Cleaned Record Count    : 7,626
Dataset Completeness    : 99.88% (Target: > 95%)
Missing Value Percentage: 0.12% (Target: < 2%)
Duplicates              : 0
============================================================
MILESTONE 1 STATUS: PASSED

In [17]:
import os

print("Current working directory:")
print(os.getcwd())

Current working directory:
c:\Users\srrikanth yadav\OneDrive\Desktop\Infosys_7.0\MedTrack_DV\notebooks

In [18]:
import os

print(os.listdir("../data/processed"))

[]

In [20]:
import os

output_path = "../data/processed/hospital_cleaned.csv"

df.to_csv(output_path, index=False)

print("Saved to:", os.path.abspath(output_path))

Saved to: c:\Users\srrikanth yadav\OneDrive\Desktop\Infosys_7.0\MedTrack_DV\data\processed\hospital_cleaned.csv