# MedTrack DV - Hospital Operations & Patient Analytics Dashboard

## Milestone 1: Data Collection, Cleaning and Integration

### Objective

To clean, preprocess, integrate hospital datasets and prepare them for KPI engineering and Tableau dashboard development.

## 1. Import Libraries

In [2]:
%pip install Faker

Defaulting to user installation because normal site-packages is not writeable
Collecting Faker
  Downloading faker-40.36.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: tzdata in c:\programdata\anaconda3\lib\site-packages (from Faker) (2025.2)
Downloading faker-40.36.0-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.1 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.1 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/2.1 MB ? eta -:--:--
   ---------- ----------------------------- 0.5/2.1 MB 481.4 kB/s eta 0:00:04
   ---------- ----------------------------- 0.5/2.1 MB 481.4 kB/s eta 0:00:04
   ---------- ----------------------------- 0.5/2.1 MB 481.4 kB/s eta 0:00:04
   --------------- ------------------------ 0.8/2.1 MB 394.3 kB/s eta 0:00:04
   --------------- ------------------------ 0.8/2.1 MB 394.3 kB/s eta 0:00:04
   -------------------- ------------------- 1.0/2.1 MB 456.1 kB/s eta 0:00:03
   ------------------------- -------------- 1.3/2.1 MB 534.5 kB/s eta 0:00:02
   ------------------------------ --------- 1.6/2.1 MB 633.4 kB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 741.7 kB/s  0:00:03
Installing collected packages: Faker
Successfully installed Faker-40.36.0
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script faker.exe is installed in 'C:\Users\keert\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [6]:
import pandas as pd
import numpy as np
import os

## 2. Load Datasets

Load all raw datasets into pandas DataFrames for data exploration and preprocessing.

In [7]:
patients = pd.read_csv("../data/01_raw_data/patients.csv")

admissions = pd.read_csv("../data/01_raw_data/admissions.csv")

doctors = pd.read_csv("../data/01_raw_data/doctors.csv")

departments = pd.read_csv("../data/01_raw_data/departments.csv")

billing = pd.read_csv("../data/01_raw_data/billing.csv")

surgeries = pd.read_csv("../data/01_raw_data/surgeries.csv")

medications = pd.read_csv("../data/01_raw_data/medications.csv")

lab_results = pd.read_csv("../data/01_raw_data/lab_results.csv")

In [8]:
print("Patients:", patients.shape)
print("Admissions:", admissions.shape)
print("Doctors:", doctors.shape)
print("Departments:", departments.shape)
print("Billing:", billing.shape)
print("Surgeries:", surgeries.shape)
print("Medications:", medications.shape)
print("Lab Results:", lab_results.shape)

Patients: (5000, 5)
Admissions: (5000, 7)
Doctors: (500, 5)
Departments: (20, 2)
Billing: (5000, 7)
Surgeries: (3505, 5)
Medications: (5000, 3)
Lab Results: (5000, 4)

In [9]:
import os

print(os.getcwd())
print(os.listdir("../data"))
print(os.listdir("../data/01_raw_data"))

C:\Users\keert\OneDrive\Desktop\internship\MedTrack_DV-Hospital-Operations-Patient-Analytics-Dashboard-\notebooks
['01_raw_data', '02_processed_data']
['admissions.csv', 'billing.csv', 'departments.csv', 'doctors.csv', 'lab_results.csv', 'medications.csv', 'patients.csv', 'surgeries.csv']

## 3. Data Exploration

This section explores the datasets to understand their structure, identify missing values, detect duplicate records, and determine the relationships between datasets before cleaning and integration.

In [10]:
datasets = {
    "Patients": patients,
    "Admissions": admissions,
    "Doctors": doctors,
    "Departments": departments,
    "Billing": billing,
    "Surgeries": surgeries,
    "Medications": medications,
    "Lab Results": lab_results
}

### 3.1 Dataset Overview

In [11]:
for name, df in datasets.items():

    print("="*70)
    print(name.upper())
    print("="*70)

    print("Shape:", df.shape)
    print("\nFirst 5 Rows:")
    display(df.head())

    print("\nColumn Names:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\n")

======================================================================
PATIENTS
======================================================================
Shape: (5000, 5)

First 5 Rows:

  Patient_ID       Name  Age  Gender Diagnosis
0     P00001  Patient_1   82  Female     Fever
1     P00002  Patient_2   31    Male  Diabetes
2     P00003  Patient_3   15    Male     Fever
3     P00004  Patient_4   50  Female    Asthma
4     P00005  Patient_5   17  Female  Diabetes

Column Names:
['Patient_ID', 'Name', 'Age', 'Gender', 'Diagnosis']

Data Types:
Patient_ID    object
Name          object
Age            int64
Gender        object
Diagnosis     object
dtype: object


======================================================================
ADMISSIONS
======================================================================
Shape: (5000, 7)

First 5 Rows:

,Admission_ID,Patient_ID,Doctor_ID,Department_ID,Admission_Date,Discharge_Date,Status
0,A00001,P00001,DR00186,D002,2025-10-20,2025-10-28,Critical
1,A00002,P00002,DR00281,D019,2025-01-21,2025-01-23,Recovered
2,A00003,P00003,DR00105,D020,2025-06-24,2025-07-03,Discharged
3,A00004,P00004,DR00312,D004,2025-07-23,2025-07-25,Critical
4,A00005,P00005,DR00430,D018,2025-04-06,2025-04-07,Under Treatment

Column Names:
['Admission_ID', 'Patient_ID', 'Doctor_ID', 'Department_ID', 'Admission_Date', 'Discharge_Date', 'Status']

Data Types:
Admission_ID      object
Patient_ID        object
Doctor_ID         object
Department_ID     object
Admission_Date    object
Discharge_Date    object
Status            object
dtype: object


======================================================================
DOCTORS
======================================================================
Shape: (500, 5)

First 5 Rows:

  Doctor_ID Doctor_Name Department_ID Specialization  Experience
0   DR00001    Doctor_1          D006            ENT           4
1   DR00002    Doctor_2          D015      Emergency          18
2   DR00003    Doctor_3          D011     Gynecology           6
3   DR00004    Doctor_4          D005       Oncology          27
4   DR00005    Doctor_5          D020         Dental          18

Column Names:
['Doctor_ID', 'Doctor_Name', 'Department_ID', 'Specialization', 'Experience']

Data Types:
Doctor_ID         object
Doctor_Name       object
Department_ID     object
Specialization    object
Experience         int64
dtype: object


======================================================================
DEPARTMENTS
======================================================================
Shape: (20, 2)

First 5 Rows:

  Department_ID Department_Name
0          D001      Cardiology
1          D002       Neurology
2          D003     Orthopedics
3          D004      Pediatrics
4          D005        Oncology

Column Names:
['Department_ID', 'Department_Name']

Data Types:
Department_ID      object
Department_Name    object
dtype: object


======================================================================
BILLING
======================================================================
Shape: (5000, 7)

First 5 Rows:

  Bill_ID Admission_ID Patient_ID  Total  Insurance   Paid  Pending
0  B00001       A00001     P00001  70078         93  70001       77
1  B00002       A00002     P00002  20824       4403  17971     2853
2  B00003       A00003     P00003   6432        239   6228      204
3  B00004       A00004     P00004  82670       9986  77817     4853
4  B00005       A00005     P00005  10376       4009   7571     2805

Column Names:
['Bill_ID', 'Admission_ID', 'Patient_ID', 'Total', 'Insurance', 'Paid', 'Pending']

Data Types:
Bill_ID         object
Admission_ID    object
Patient_ID      object
Total            int64
Insurance        int64
Paid             int64
Pending          int64
dtype: object


======================================================================
SURGERIES
======================================================================
Shape: (3505, 5)

First 5 Rows:

  Surgery_ID Admission_ID Patient_ID Doctor_ID       Outcome
0     S00001       A00001     P00001   DR00186       Success
1     S00002       A00002     P00002   DR00281  Complication
2     S00003       A00003     P00003   DR00105  Complication
3     S00004       A00004     P00004   DR00312  Complication
4     S00005       A00005     P00005   DR00430  Complication

Column Names:
['Surgery_ID', 'Admission_ID', 'Patient_ID', 'Doctor_ID', 'Outcome']

Data Types:
Surgery_ID      object
Admission_ID    object
Patient_ID      object
Doctor_ID       object
Outcome         object
dtype: object


======================================================================
MEDICATIONS
======================================================================
Shape: (5000, 3)

First 5 Rows:

  Medication_ID Admission_ID   Medicine
0        M00001       A00001  Ibuprofen
1        M00002       A00002  Ibuprofen
2        M00003       A00003  Ibuprofen
3        M00004       A00004    Insulin
4        M00005       A00005  Ibuprofen

Column Names:
['Medication_ID', 'Admission_ID', 'Medicine']

Data Types:
Medication_ID    object
Admission_ID     object
Medicine         object
dtype: object


======================================================================
LAB RESULTS
======================================================================
Shape: (5000, 4)

First 5 Rows:

   Lab_ID Admission_ID         Test   Value
0  L00001       A00001  Blood Sugar   91.27
1  L00002       A00002  Blood Sugar  175.69
2  L00003       A00003  Cholesterol  150.60
3  L00004       A00004  Cholesterol  176.53
4  L00005       A00005  Blood Sugar  133.46

Column Names:
['Lab_ID', 'Admission_ID', 'Test', 'Value']

Data Types:
Lab_ID           object
Admission_ID     object
Test             object
Value           float64
dtype: object

### 3.2 Missing Value Analysis

In [12]:
for name, df in datasets.items():

    print("="*70)
    print(name)

    print(df.isnull().sum())
    print()

======================================================================
Patients
Patient_ID    0
Name          0
Age           0
Gender        0
Diagnosis     0
dtype: int64

======================================================================
Admissions
Admission_ID      0
Patient_ID        0
Doctor_ID         0
Department_ID     0
Admission_Date    0
Discharge_Date    0
Status            0
dtype: int64

======================================================================
Doctors
Doctor_ID         0
Doctor_Name       0
Department_ID     0
Specialization    0
Experience        0
dtype: int64

======================================================================
Departments
Department_ID      0
Department_Name    0
dtype: int64

======================================================================
Billing
Bill_ID         0
Admission_ID    0
Patient_ID      0
Total           0
Insurance       0
Paid            0
Pending         0
dtype: int64

======================================================================
Surgeries
Surgery_ID      0
Admission_ID    0
Patient_ID      0
Doctor_ID       0
Outcome         0
dtype: int64

======================================================================
Medications
Medication_ID    0
Admission_ID     0
Medicine         0
dtype: int64

======================================================================
Lab Results
Lab_ID          0
Admission_ID    0
Test            0
Value           0
dtype: int64

### 3.3 Duplicate Records

In [13]:
for name, df in datasets.items():

    print(name)
    print("Duplicate Rows:", df.duplicated().sum())
    print()

Patients
Duplicate Rows: 0

Admissions
Duplicate Rows: 0

Doctors
Duplicate Rows: 0

Departments
Duplicate Rows: 0

Billing
Duplicate Rows: 0

Surgeries
Duplicate Rows: 0

Medications
Duplicate Rows: 0

Lab Results
Duplicate Rows: 0

### 3.5 Dataset Information

In [14]:
for name, df in datasets.items():

    print("="*70)
    print(name)
    print("="*70)

    df.info()

    print("\n")

======================================================================
Patients
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Patient_ID  5000 non-null   object
 1   Name        5000 non-null   object
 2   Age         5000 non-null   int64
 3   Gender      5000 non-null   object
 4   Diagnosis   5000 non-null   object
dtypes: int64(1), object(4)
memory usage: 195.4+ KB


======================================================================
Admissions
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Admission_ID    5000 non-null   object
 1   Patient_ID      5000 non-null   object
 2   Doctor_ID       5000 non-null   object
 3   Department_ID   5000 non-null   object
 4   Admission_Date  5000 non-null   object
 5   Discharge_Date  5000 non-null   object
 6   Status          5000 non-null   object
dtypes: object(7)
memory usage: 273.6+ KB


======================================================================
Doctors
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Doctor_ID       500 non-null    object
 1   Doctor_Name     500 non-null    object
 2   Department_ID   500 non-null    object
 3   Specialization  500 non-null    object
 4   Experience      500 non-null    int64
dtypes: int64(1), object(4)
memory usage: 19.7+ KB


======================================================================
Departments
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Department_ID    20 non-null     object
 1   Department_Name  20 non-null     object
dtypes: object(2)
memory usage: 452.0+ bytes


======================================================================
Billing
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Bill_ID       5000 non-null   object
 1   Admission_ID  5000 non-null   object
 2   Patient_ID    5000 non-null   object
 3   Total         5000 non-null   int64
 4   Insurance     5000 non-null   int64
 5   Paid          5000 non-null   int64
 6   Pending       5000 non-null   int64
dtypes: int64(4), object(3)
memory usage: 273.6+ KB


======================================================================
Surgeries
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3505 entries, 0 to 3504
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Surgery_ID    3505 non-null   object
 1   Admission_ID  3505 non-null   object
 2   Patient_ID    3505 non-null   object
 3   Doctor_ID     3505 non-null   object
 4   Outcome       3505 non-null   object
dtypes: object(5)
memory usage: 137.0+ KB


======================================================================
Medications
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Medication_ID  5000 non-null   object
 1   Admission_ID   5000 non-null   object
 2   Medicine       5000 non-null   object
dtypes: object(3)
memory usage: 117.3+ KB


======================================================================
Lab Results
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Lab_ID        5000 non-null   object
 1   Admission_ID  5000 non-null   object
 2   Test          5000 non-null   object
 3   Value         5000 non-null   float64
dtypes: float64(1), object(3)
memory usage: 156.4+ KB

### 3.6 Statistical Summary

In [15]:
for name, df in datasets.items():

    print("="*70)
    print(name)
    print("="*70)

    display(df.describe(include="all"))

======================================================================
Patients
======================================================================

       Patient_ID       Name          Age  Gender Diagnosis
count        5000       5000  5000.000000    5000      5000
unique       5000       5000          NaN       2         4
top        P00001  Patient_1          NaN  Female    Cancer
freq            1          1          NaN    2519      1280
mean          NaN        NaN    45.734400     NaN       NaN
std           NaN        NaN    26.080496     NaN       NaN
min           NaN        NaN     1.000000     NaN       NaN
25%           NaN        NaN    23.000000     NaN       NaN
50%           NaN        NaN    46.000000     NaN       NaN
75%           NaN        NaN    68.000000     NaN       NaN
max           NaN        NaN    90.000000     NaN       NaN

======================================================================
Admissions
======================================================================

,Admission_ID,Patient_ID,Doctor_ID,Department_ID,Admission_Date,Discharge_Date,Status
count,5000,5000,5000,5000,5000,5000,5000
unique,5000,5000,500,20,301,309,4
top,A00001,P00001,DR00039,D015,2025-05-12,2025-04-07,Critical
freq,1,1,21,335,29,28,1279

======================================================================
Doctors
======================================================================

       Doctor_ID Doctor_Name Department_ID Specialization  Experience
count        500         500           500            500  500.000000
unique       500         500            20             20         NaN
top      DR00001    Doctor_1          D015      Emergency         NaN
freq           1           1            34             34         NaN
mean         NaN         NaN           NaN            NaN   18.004000
std          NaN         NaN           NaN            NaN   10.401941
min          NaN         NaN           NaN            NaN    1.000000
25%          NaN         NaN           NaN            NaN    9.000000
50%          NaN         NaN           NaN            NaN   19.000000
75%          NaN         NaN           NaN            NaN   27.000000
max          NaN         NaN           NaN            NaN   35.000000

======================================================================
Departments
======================================================================

       Department_ID Department_Name
count             20              20
unique            20              20
top             D001      Cardiology
freq               1               1

======================================================================
Billing
======================================================================

,Bill_ID,Admission_ID,Patient_ID,Total,Insurance,Paid,Pending
count,5000,5000,5000,5000.000000,5000.000000,5000.000000,5000.000000
unique,5000,5000,5000,NaN,NaN,NaN,NaN
top,B00001,A00001,P00001,NaN,NaN,NaN,NaN
freq,1,1,1,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,52678.621000,13340.769200,45891.751200,6786.869800
std,NaN,NaN,NaN,27339.548025,11130.274534,24566.583764,7647.151196
min,NaN,NaN,NaN,5014.000000,7.000000,3346.000000,0.000000
25%,NaN,NaN,NaN,29204.500000,4175.250000,25112.000000,1290.000000
50%,NaN,NaN,NaN,52589.500000,10115.500000,45030.000000,3845.000000
75%,NaN,NaN,NaN,76650.000000,20510.000000,65466.750000,9762.000000
max,NaN,NaN,NaN,99987.000000,48883.000000,99644.000000,44464.000000

======================================================================
Surgeries
======================================================================

       Surgery_ID Admission_ID Patient_ID Doctor_ID       Outcome
count        3505         3505       3505      3505          3505
unique       3505         3505       3505       500             3
top        S00001       A00001     P00001   DR00168  Complication
freq            1            1          1        15          1217

======================================================================
Medications
======================================================================

       Medication_ID Admission_ID   Medicine
count           5000         5000       5000
unique          5000         5000          3
top           M00001       A00001  Ibuprofen
freq               1            1       1692

======================================================================
Lab Results
======================================================================

        Lab_ID Admission_ID         Test        Value
count     5000         5000         5000  5000.000000
unique    5000         5000            2          NaN
top     L00001       A00001  Blood Sugar          NaN
freq         1            1         2567          NaN
mean       NaN          NaN          NaN   135.021008
std        NaN          NaN          NaN    38.168462
min        NaN          NaN          NaN    70.040000
25%        NaN          NaN          NaN   101.177500
50%        NaN          NaN          NaN   135.610000
75%        NaN          NaN          NaN   168.802500
max        NaN          NaN          NaN   199.940000

## 4. Key Validation

In [16]:
print("Patients Patient_ID:", patients["Patient_ID"].is_unique)
print("Admissions Admission_ID:", admissions["Admission_ID"].is_unique)
print("Doctors Doctor_ID:", doctors["Doctor_ID"].is_unique)
print("Departments Department_ID:", departments["Department_ID"].is_unique)
print("Billing Bill_ID:", billing["Bill_ID"].is_unique)
print("Surgeries Surgery_ID:", surgeries["Surgery_ID"].is_unique)
print("Medications Medication_ID:", medications["Medication_ID"].is_unique)
print("Lab Results Lab_ID:", lab_results["Lab_ID"].is_unique)

Patients Patient_ID: True
Admissions Admission_ID: True
Doctors Doctor_ID: True
Departments Department_ID: True
Billing Bill_ID: True
Surgeries Surgery_ID: True
Medications Medication_ID: True
Lab Results Lab_ID: True

In [17]:
print("Patients in Admissions:",
      admissions["Patient_ID"].isin(patients["Patient_ID"]).all())
print("Doctors in Admissions:",
      admissions["Doctor_ID"].isin(doctors["Doctor_ID"]).all())
print("Departments in Admissions:",
      admissions["Department_ID"].isin(departments["Department_ID"]).all())
print("Admissions in Billing:",
      billing["Admission_ID"].isin(admissions["Admission_ID"]).all())
print("Admissions in Surgeries:",
      surgeries["Admission_ID"].isin(admissions["Admission_ID"]).all())
print("Admissions in Medications:",
      medications["Admission_ID"].isin(admissions["Admission_ID"]).all())
print("Admissions in Lab Results:",
      lab_results["Admission_ID"].isin(admissions["Admission_ID"]).all())

Patients in Admissions: True
Doctors in Admissions: True
Departments in Admissions: True
Admissions in Billing: True
Admissions in Surgeries: True
Admissions in Medications: True
Admissions in Lab Results: True

## 4. Data Cleaning

Standardize column names across all datasets to maintain consistency.

In [18]:
for name, df in datasets.items():

    df.columns = (
        df.columns
          .str.strip()
          .str.replace(" ", "_", regex=False)
          .str.replace("(", "", regex=False)
          .str.replace(")", "", regex=False)
          .str.replace("-", "_", regex=False)
    )

print(" Column names standardized.")

 Column names standardized.

### Remove Leading and Trailing Spaces

In [19]:
for name, df in datasets.items():

    text_cols = df.select_dtypes(include="object").columns

    for col in text_cols:
        df[col] = df[col].str.strip()

print("Extra spaces removed.")

Extra spaces removed.

### Remove Duplicate Records

In [20]:
for name, df in datasets.items():

    before = len(df)

    df.drop_duplicates(inplace=True)

    after = len(df)

    print(f"{name}: {before-after} duplicate rows removed.")

Patients: 0 duplicate rows removed.
Admissions: 0 duplicate rows removed.
Doctors: 0 duplicate rows removed.
Departments: 0 duplicate rows removed.
Billing: 0 duplicate rows removed.
Surgeries: 0 duplicate rows removed.
Medications: 0 duplicate rows removed.
Lab Results: 0 duplicate rows removed.

### Convert Date Columns

In [21]:
admissions["Admission_Date"] = pd.to_datetime(admissions["Admission_Date"])
admissions["Discharge_Date"] = pd.to_datetime(admissions["Discharge_Date"])

print(admissions.dtypes)

Admission_ID              object
Patient_ID                object
Doctor_ID                 object
Department_ID             object
Admission_Date    datetime64[ns]
Discharge_Date    datetime64[ns]
Status                    object
dtype: object

In [22]:
for name, df in datasets.items():

    print("="*60)
    print(name)

    print("Missing Values :", df.isnull().sum().sum())
    print("Duplicate Rows :", df.duplicated().sum())

============================================================
Patients
Missing Values : 0
Duplicate Rows : 0
============================================================
Admissions
Missing Values : 0
Duplicate Rows : 0
============================================================
Doctors
Missing Values : 0
Duplicate Rows : 0
============================================================
Departments
Missing Values : 0
Duplicate Rows : 0
============================================================
Billing
Missing Values : 0
Duplicate Rows : 0
============================================================
Surgeries
Missing Values : 0
Duplicate Rows : 0
============================================================
Medications
Missing Values : 0
Duplicate Rows : 0
============================================================
Lab Results
Missing Values : 0
Duplicate Rows : 0

## 5. Feature Engineering

In [24]:
admissions["Length_of_Stay"] = (
    admissions["Discharge_Date"] -
    admissions["Admission_Date"]
).dt.days

In [25]:
admissions["Admission_Year"] = admissions["Admission_Date"].dt.year

In [26]:
admissions["Admission_Month"] = admissions["Admission_Date"].dt.month_name()

In [27]:
admissions["Admission_Quarter"] = admissions["Admission_Date"].dt.quarter

In [28]:
admissions["Weekend_Admission"] = (
    admissions["Admission_Date"].dt.dayofweek >= 5
)

In [29]:
admissions["Stay_Category"] = pd.cut(
    admissions["Length_of_Stay"],
    bins=[0,3,7,15,100],
    labels=["Short","Medium","Long","Extended"]
)

In [30]:
patients["Age_Group"] = pd.cut(
    patients["Age"],
    bins=[0,18,35,60,100],
    labels=["Child","Young Adult","Adult","Senior"]
)

In [31]:
print(admissions.head())
print(patients.head())

  Admission_ID Patient_ID Doctor_ID Department_ID Admission_Date  \
0       A00001     P00001   DR00186          D002     2025-10-20
1       A00002     P00002   DR00281          D019     2025-01-21
2       A00003     P00003   DR00105          D020     2025-06-24
3       A00004     P00004   DR00312          D004     2025-07-23
4       A00005     P00005   DR00430          D018     2025-04-06

  Discharge_Date           Status  Length_of_Stay  Admission_Year  \
0     2025-10-28         Critical               8            2025
1     2025-01-23        Recovered               2            2025
2     2025-07-03       Discharged               9            2025
3     2025-07-25         Critical               2            2025
4     2025-04-07  Under Treatment               1            2025

  Admission_Month  Admission_Quarter  Weekend_Admission Stay_Category
0         October                  4              False          Long
1         January                  1              False         Short
2            June                  2              False          Long
3            July                  3              False         Short
4           April                  2               True         Short
  Patient_ID       Name  Age  Gender Diagnosis    Age_Group
0     P00001  Patient_1   82  Female     Fever       Senior
1     P00002  Patient_2   31    Male  Diabetes  Young Adult
2     P00003  Patient_3   15    Male     Fever        Child
3     P00004  Patient_4   50  Female    Asthma        Adult
4     P00005  Patient_5   17  Female  Diabetes        Child

## 6. Data Integration

Merge all datasets using their verified primary and foreign keys to create a master hospital dataset.

In [32]:
patient_master = patients.merge(
    admissions,
    on="Patient_ID",
    how="inner"
)

print("Shape:", patient_master.shape)
patient_master.head()

Shape: (5000, 18)

,Patient_ID,Name,Age,Gender,Diagnosis,Age_Group,Admission_ID,Doctor_ID,Department_ID,Admission_Date,Discharge_Date,Status,Length_of_Stay,Admission_Year,Admission_Month,Admission_Quarter,Weekend_Admission,Stay_Category
0,P00001,Patient_1,82,Female,Fever,Senior,A00001,DR00186,D002,2025-10-20,2025-10-28,Critical,8,2025,October,4,False,Long
1,P00002,Patient_2,31,Male,Diabetes,Young Adult,A00002,DR00281,D019,2025-01-21,2025-01-23,Recovered,2,2025,January,1,False,Short
2,P00003,Patient_3,15,Male,Fever,Child,A00003,DR00105,D020,2025-06-24,2025-07-03,Discharged,9,2025,June,2,False,Long
3,P00004,Patient_4,50,Female,Asthma,Adult,A00004,DR00312,D004,2025-07-23,2025-07-25,Critical,2,2025,July,3,False,Short
4,P00005,Patient_5,17,Female,Diabetes,Child,A00005,DR00430,D018,2025-04-06,2025-04-07,Under Treatment,1,2025,April,2,True,Short

In [33]:
print("Missing Values:", patient_master.isnull().sum().sum())
print("Duplicate Rows:", patient_master.duplicated().sum())

Missing Values: 0
Duplicate Rows: 0

In [34]:
patient_master = patient_master.merge(
    doctors,
    on="Doctor_ID",
    how="left"
)

print(patient_master.shape)

(5000, 22)

In [35]:
print(patient_master.isnull().sum())

Patient_ID           0
Name                 0
Age                  0
Gender               0
Diagnosis            0
Age_Group            0
Admission_ID         0
Doctor_ID            0
Department_ID_x      0
Admission_Date       0
Discharge_Date       0
Status               0
Length_of_Stay       0
Admission_Year       0
Admission_Month      0
Admission_Quarter    0
Weekend_Admission    0
Stay_Category        0
Doctor_Name          0
Department_ID_y      0
Specialization       0
Experience           0
dtype: int64

In [36]:
patient_master = patient_master.merge(
    departments,
    on="Department_ID",
    how="left"
)

print(patient_master.shape)

KeyError: 'Department_ID'

In [41]:
print(patient_master.columns.tolist())

['Patient_ID', 'Name', 'Age', 'Gender', 'Diagnosis', 'Age_Group', 'Admission_ID', 'Doctor_ID', 'Department_ID_x', 'Admission_Date', 'Discharge_Date', 'Status', 'Length_of_Stay', 'Admission_Year', 'Admission_Month', 'Admission_Quarter', 'Weekend_Admission', 'Stay_Category', 'Doctor_Name', 'Department_ID_y', 'Specialization', 'Experience', 'Bill_ID', 'Total', 'Insurance', 'Paid', 'Pending', 'Surgery_ID', 'Outcome', 'Medication_ID', 'Medicine', 'Lab_ID', 'Test', 'Value']

In [42]:
print(patient_master[["Department_ID_x", "Department_ID_y"]].head())

print(
    (patient_master["Department_ID_x"] == patient_master["Department_ID_y"]).all()
)

  Department_ID_x Department_ID_y
0            D002            D002
1            D019            D019
2            D020            D020
3            D004            D004
4            D018            D018
True

In [43]:
patient_master.drop(columns=["Department_ID_y"], inplace=True)

patient_master.rename(
    columns={"Department_ID_x": "Department_ID"},
    inplace=True
)

In [44]:
print(patient_master.columns.tolist())

['Patient_ID', 'Name', 'Age', 'Gender', 'Diagnosis', 'Age_Group', 'Admission_ID', 'Doctor_ID', 'Department_ID', 'Admission_Date', 'Discharge_Date', 'Status', 'Length_of_Stay', 'Admission_Year', 'Admission_Month', 'Admission_Quarter', 'Weekend_Admission', 'Stay_Category', 'Doctor_Name', 'Specialization', 'Experience', 'Bill_ID', 'Total', 'Insurance', 'Paid', 'Pending', 'Surgery_ID', 'Outcome', 'Medication_ID', 'Medicine', 'Lab_ID', 'Test', 'Value']

In [45]:
patient_master = patient_master.merge(
    departments,
    on="Department_ID",
    how="left",
    validate="many_to_one"
)

print(patient_master.shape)

(5000, 34)

In [47]:
print(patient_master[[
    "Department_ID",
    "Department_Name"
]].head())

  Department_ID Department_Name
0          D002       Neurology
1          D019   Endocrinology
2          D020          Dental
3          D004      Pediatrics
4          D018   Ophthalmology

In [48]:
patient_master = patient_master.merge(
    billing,
    on=["Admission_ID", "Patient_ID"],
    how="left"
)

print(patient_master.shape)

(5000, 39)

In [49]:
patient_master = patient_master.merge(
    surgeries,
    on=["Admission_ID", "Patient_ID", "Doctor_ID"],
    how="left",
    suffixes=("", "_Surgery")
)

print(patient_master.shape)

(5000, 41)

In [50]:
patient_master = patient_master.merge(
    medications,
    on="Admission_ID",
    how="left"
)

print(patient_master.shape)

(5000, 43)

In [51]:
patient_master = patient_master.merge(
    lab_results,
    on="Admission_ID",
    how="left",
    suffixes=("", "_Lab")
)

print(patient_master.shape)

(5000, 46)

In [52]:
# Admissions → Doctors
validate="many_to_one"

# Admissions → Departments
validate="many_to_one"

# Admissions → Billing
validate="one_to_one"

# Admissions → Surgeries
validate="one_to_one"

# Admissions → Medications
validate="one_to_one"

# Admissions → Lab Results
validate="one_to_one"

In [53]:
patient_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 46 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Patient_ID          5000 non-null   object
 1   Name                5000 non-null   object
 2   Age                 5000 non-null   int64
 3   Gender              5000 non-null   object
 4   Diagnosis           5000 non-null   object
 5   Age_Group           5000 non-null   category
 6   Admission_ID        5000 non-null   object
 7   Doctor_ID           5000 non-null   object
 8   Department_ID       5000 non-null   object
 9   Admission_Date      5000 non-null   datetime64[ns]
 10  Discharge_Date      5000 non-null   datetime64[ns]
 11  Status              5000 non-null   object
 12  Length_of_Stay      5000 non-null   int64
 13  Admission_Year      5000 non-null   int32
 14  Admission_Month     5000 non-null   object
 15  Admission_Quarter   5000 non-null   int32
 16  Weekend_Admission   5000 non-null   bool
 17  Stay_Category       5000 non-null   category
 18  Doctor_Name         5000 non-null   object
 19  Specialization      5000 non-null   object
 20  Experience          5000 non-null   int64
 21  Bill_ID_x           5000 non-null   object
 22  Total_x             5000 non-null   int64
 23  Insurance_x         5000 non-null   int64
 24  Paid_x              5000 non-null   int64
 25  Pending_x           5000 non-null   int64
 26  Surgery_ID          3505 non-null   object
 27  Outcome             3505 non-null   object
 28  Medication_ID_x     5000 non-null   object
 29  Medicine_x          5000 non-null   object
 30  Lab_ID              5000 non-null   object
 31  Test                5000 non-null   object
 32  Value               5000 non-null   float64
 33  Department_Name     5000 non-null   object
 34  Bill_ID_y           5000 non-null   object
 35  Total_y             5000 non-null   int64
 36  Insurance_y         5000 non-null   int64
 37  Paid_y              5000 non-null   int64
 38  Pending_y           5000 non-null   int64
 39  Surgery_ID_Surgery  3505 non-null   object
 40  Outcome_Surgery     3505 non-null   object
 41  Medication_ID_y     5000 non-null   object
 42  Medicine_y          5000 non-null   object
 43  Lab_ID_Lab          5000 non-null   object
 44  Test_Lab            5000 non-null   object
 45  Value_Lab           5000 non-null   float64
dtypes: bool(1), category(2), datetime64[ns](2), float64(2), int32(2), int64(11), object(26)
memory usage: 1.6+ MB

In [54]:
print((patient_master["Bill_ID_x"] == patient_master["Bill_ID_y"]).all())

print((patient_master["Medication_ID_x"] == patient_master["Medication_ID_y"]).all())

print((patient_master["Medicine_x"] == patient_master["Medicine_y"]).all())

print((patient_master["Lab_ID"] == patient_master["Lab_ID_Lab"]).all())

print((patient_master["Test"] == patient_master["Test_Lab"]).all())

print((patient_master["Value"] == patient_master["Value_Lab"]).all())

True
True
True
True
True
True

In [55]:
print(
    patient_master["Surgery_ID"].fillna("NA").equals(
        patient_master["Surgery_ID_Surgery"].fillna("NA")
    )
)

print(
    patient_master["Outcome"].fillna("NA").equals(
        patient_master["Outcome_Surgery"].fillna("NA")
    )
)

True
True

In [56]:
patient_master.drop(columns=[
    "Bill_ID_y",
    "Total_y",
    "Insurance_y",
    "Paid_y",
    "Pending_y",

    "Medication_ID_y",
    "Medicine_y",

    "Lab_ID_Lab",
    "Test_Lab",
    "Value_Lab",

    "Surgery_ID_Surgery",
    "Outcome_Surgery"
], inplace=True)

In [57]:
patient_master.rename(columns={
    "Bill_ID_x":"Bill_ID",
    "Total_x":"Total",
    "Insurance_x":"Insurance",
    "Paid_x":"Paid",
    "Pending_x":"Pending",

    "Medication_ID_x":"Medication_ID",
    "Medicine_x":"Medicine"
}, inplace=True)

In [58]:
patient_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 34 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient_ID         5000 non-null   object
 1   Name               5000 non-null   object
 2   Age                5000 non-null   int64
 3   Gender             5000 non-null   object
 4   Diagnosis          5000 non-null   object
 5   Age_Group          5000 non-null   category
 6   Admission_ID       5000 non-null   object
 7   Doctor_ID          5000 non-null   object
 8   Department_ID      5000 non-null   object
 9   Admission_Date     5000 non-null   datetime64[ns]
 10  Discharge_Date     5000 non-null   datetime64[ns]
 11  Status             5000 non-null   object
 12  Length_of_Stay     5000 non-null   int64
 13  Admission_Year     5000 non-null   int32
 14  Admission_Month    5000 non-null   object
 15  Admission_Quarter  5000 non-null   int32
 16  Weekend_Admission  5000 non-null   bool
 17  Stay_Category      5000 non-null   category
 18  Doctor_Name        5000 non-null   object
 19  Specialization     5000 non-null   object
 20  Experience         5000 non-null   int64
 21  Bill_ID            5000 non-null   object
 22  Total              5000 non-null   int64
 23  Insurance          5000 non-null   int64
 24  Paid               5000 non-null   int64
 25  Pending            5000 non-null   int64
 26  Surgery_ID         3505 non-null   object
 27  Outcome            3505 non-null   object
 28  Medication_ID      5000 non-null   object
 29  Medicine           5000 non-null   object
 30  Lab_ID             5000 non-null   object
 31  Test               5000 non-null   object
 32  Value              5000 non-null   float64
 33  Department_Name    5000 non-null   object
dtypes: bool(1), category(2), datetime64[ns](2), float64(1), int32(2), int64(7), object(19)
memory usage: 1.2+ MB

In [59]:
print(patient_master.isnull().sum())

Patient_ID              0
Name                    0
Age                     0
Gender                  0
Diagnosis               0
Age_Group               0
Admission_ID            0
Doctor_ID               0
Department_ID           0
Admission_Date          0
Discharge_Date          0
Status                  0
Length_of_Stay          0
Admission_Year          0
Admission_Month         0
Admission_Quarter       0
Weekend_Admission       0
Stay_Category           0
Doctor_Name             0
Specialization          0
Experience              0
Bill_ID                 0
Total                   0
Insurance               0
Paid                    0
Pending                 0
Surgery_ID           1495
Outcome              1495
Medication_ID           0
Medicine                0
Lab_ID                  0
Test                    0
Value                   0
Department_Name         0
dtype: int64

In [60]:
print("Duplicate Rows:", patient_master.duplicated().sum())

print("Unique Patients:", patient_master["Patient_ID"].nunique())

print("Unique Admissions:", patient_master["Admission_ID"].nunique())

print("Unique Doctors:", patient_master["Doctor_ID"].nunique())

print("Unique Departments:", patient_master["Department_ID"].nunique())

Duplicate Rows: 0
Unique Patients: 5000
Unique Admissions: 5000
Unique Doctors: 500
Unique Departments: 20

In [61]:
import os

os.makedirs("../data/02_processed_data", exist_ok=True)

patient_master.to_csv(
    "../data/02_processed_data/hospital_master_dataset.csv",
    index=False
)

print("hospital_master_dataset.csv saved successfully!")

hospital_master_dataset.csv saved successfully!

In [62]:
data_dictionary = pd.DataFrame({
    "Column_Name": patient_master.columns,
    "Data_Type": patient_master.dtypes.astype(str),
    "Missing_Values": patient_master.isnull().sum().values
})

data_dictionary.to_csv(
    "../data/02_processed_data/data_dictionary.csv",
    index=False
)

data_dictionary

                         Column_Name       Data_Type  Missing_Values
Patient_ID                Patient_ID          object               0
Name                            Name          object               0
Age                              Age           int64               0
Gender                        Gender          object               0
Diagnosis                  Diagnosis          object               0
Age_Group                  Age_Group        category               0
Admission_ID            Admission_ID          object               0
Doctor_ID                  Doctor_ID          object               0
Department_ID          Department_ID          object               0
Admission_Date        Admission_Date  datetime64[ns]               0
Discharge_Date        Discharge_Date  datetime64[ns]               0
Status                        Status          object               0
Length_of_Stay        Length_of_Stay           int64               0
Admission_Year        Admission_Year           int32               0
Admission_Month      Admission_Month          object               0
Admission_Quarter  Admission_Quarter           int32               0
Weekend_Admission  Weekend_Admission            bool               0
Stay_Category          Stay_Category        category               0
Doctor_Name              Doctor_Name          object               0
Specialization        Specialization          object               0
Experience                Experience           int64               0
Bill_ID                      Bill_ID          object               0
Total                          Total           int64               0
Insurance                  Insurance           int64               0
Paid                            Paid           int64               0
Pending                      Pending           int64               0
Surgery_ID                Surgery_ID          object            1495
Outcome                      Outcome          object            1495
Medication_ID          Medication_ID          object               0
Medicine                    Medicine          object               0
Lab_ID                        Lab_ID          object               0
Test                            Test          object               0
Value                          Value         float64               0
Department_Name      Department_Name          object               0

# Save Cleaned Datasets

The cleaned and processed datasets are saved for use in the next stages of the MedTrack project.

In [69]:
import os
os.makedirs("../data/02_processed_data", exist_ok=True)

In [70]:
patients.to_csv("../data/02_processed_data/patients_cleaned.csv", index=False)
admissions.to_csv("../data/02_processed_data/admissions_cleaned.csv", index=False)
doctors.to_csv("../data/02_processed_data/doctors_cleaned.csv", index=False)
departments.to_csv("../data/02_processed_data/departments_cleaned.csv", index=False)
billing.to_csv("../data/02_processed_data/billing_cleaned.csv", index=False)
surgeries.to_csv("../data/02_processed_data/surgeries_cleaned.csv", index=False)
medications.to_csv("../data/02_processed_data/medications_cleaned.csv", index=False)
lab_results.to_csv("../data/02_processed_data/lab_results_cleaned.csv", index=False)
patient_master.to_csv("../data/02_processed_data/hospital_master_dataset.csv", index=False)
print("All cleaned datasets saved successfully.")

All cleaned datasets saved successfully.

## Conclusion

- Successfully collected and explored all datasets.
- Standardized and cleaned the data.
- Engineered new analytical features.
- Integrated datasets into a single master dataset.
- Validated data quality and relationships.
- Exported the cleaned dataset for dashboard development.