# Master Dataset Creation

This notebook creates specialized master datasets from the cleaned Hospital Master Dataset.

Master Datasets:
- Doctor Master
- Billing Master
- Bed Master

In [1]:
import pandas as pd
import numpy as np
import random

In [2]:
hospital_master = pd.read_csv(
    "../data/02_processed_data/hospital_master_dataset.csv",
    parse_dates=["Admission_Date", "Discharge_Date"]
)

In [3]:
hospital_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 34 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient_ID         5000 non-null   object
 1   Name               5000 non-null   object
 2   Age                5000 non-null   int64
 3   Gender             5000 non-null   object
 4   Diagnosis          5000 non-null   object
 5   Age_Group          5000 non-null   object
 6   Admission_ID       5000 non-null   object
 7   Doctor_ID          5000 non-null   object
 8   Department_ID      5000 non-null   object
 9   Admission_Date     5000 non-null   datetime64[ns]
 10  Discharge_Date     5000 non-null   datetime64[ns]
 11  Status             5000 non-null   object
 12  Length_of_Stay     5000 non-null   int64
 13  Admission_Year     5000 non-null   int64
 14  Admission_Month    5000 non-null   object
 15  Admission_Quarter  5000 non-null   int64
 16  Weekend_Admission  5000 non-null   bool
 17  Stay_Category      5000 non-null   object
 18  Doctor_Name        5000 non-null   object
 19  Specialization     5000 non-null   object
 20  Experience         5000 non-null   int64
 21  Bill_ID            5000 non-null   object
 22  Total              5000 non-null   int64
 23  Insurance          5000 non-null   int64
 24  Paid               5000 non-null   int64
 25  Pending            5000 non-null   int64
 26  Surgery_ID         3505 non-null   object
 27  Outcome            3505 non-null   object
 28  Medication_ID      5000 non-null   object
 29  Medicine           5000 non-null   object
 30  Lab_ID             5000 non-null   object
 31  Test               5000 non-null   object
 32  Value              5000 non-null   float64
 33  Department_Name    5000 non-null   object
dtypes: bool(1), datetime64[ns](2), float64(1), int64(9), object(21)
memory usage: 1.3+ MB

## Doctor Master Dataset

In [4]:
doctor_master = hospital_master[
    [
        "Doctor_ID",
        "Doctor_Name",
        "Department_ID",
        "Department_Name",
        "Specialization",
        "Experience",
        "Patient_ID",
        "Name",
        "Age",
        "Gender",
        "Diagnosis",
        "Admission_ID",
        "Admission_Date",
        "Discharge_Date",
        "Length_of_Stay",
        "Status"
    ]
].copy()

In [5]:
doctor_master.head()

,Doctor_ID,Doctor_Name,Department_ID,Department_Name,Specialization,Experience,Patient_ID,Name,Age,Gender,Diagnosis,Admission_ID,Admission_Date,Discharge_Date,Length_of_Stay,Status
0,DR00186,Doctor_186,D002,Neurology,Neurology,2,P00001,Patient_1,82,Female,Fever,A00001,2025-10-20,2025-10-28,8,Critical
1,DR00281,Doctor_281,D019,Endocrinology,Endocrinology,15,P00002,Patient_2,31,Male,Diabetes,A00002,2025-01-21,2025-01-23,2,Recovered
2,DR00105,Doctor_105,D020,Dental,Dental,33,P00003,Patient_3,15,Male,Fever,A00003,2025-06-24,2025-07-03,9,Discharged
3,DR00312,Doctor_312,D004,Pediatrics,Pediatrics,34,P00004,Patient_4,50,Female,Asthma,A00004,2025-07-23,2025-07-25,2,Critical
4,DR00430,Doctor_430,D018,Ophthalmology,Ophthalmology,4,P00005,Patient_5,17,Female,Diabetes,A00005,2025-04-06,2025-04-07,1,Under Treatment

In [6]:
doctor_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Doctor_ID        5000 non-null   object
 1   Doctor_Name      5000 non-null   object
 2   Department_ID    5000 non-null   object
 3   Department_Name  5000 non-null   object
 4   Specialization   5000 non-null   object
 5   Experience       5000 non-null   int64
 6   Patient_ID       5000 non-null   object
 7   Name             5000 non-null   object
 8   Age              5000 non-null   int64
 9   Gender           5000 non-null   object
 10  Diagnosis        5000 non-null   object
 11  Admission_ID     5000 non-null   object
 12  Admission_Date   5000 non-null   datetime64[ns]
 13  Discharge_Date   5000 non-null   datetime64[ns]
 14  Length_of_Stay   5000 non-null   int64
 15  Status           5000 non-null   object
dtypes: datetime64[ns](2), int64(3), object(11)
memory usage: 625.1+ KB

In [7]:
doctor_master.to_csv(
    "../data/02_processed_data/doctor_master.csv",
    index=False
)

## Billing Master Dataset

In [8]:
billing_master = hospital_master[
    [
        "Bill_ID",
        "Admission_ID",
        "Patient_ID",
        "Name",
        "Age",
        "Gender",
        "Department_Name",
        "Doctor_Name",
        "Total",
        "Insurance",
        "Paid",
        "Pending",
        "Admission_Date",
        "Discharge_Date",
        "Length_of_Stay"
    ]
].copy()

In [9]:
billing_master.head()

,Bill_ID,Admission_ID,Patient_ID,Name,Age,Gender,Department_Name,Doctor_Name,Total,Insurance,Paid,Pending,Admission_Date,Discharge_Date,Length_of_Stay
0,B00001,A00001,P00001,Patient_1,82,Female,Neurology,Doctor_186,70078,93,70001,77,2025-10-20,2025-10-28,8
1,B00002,A00002,P00002,Patient_2,31,Male,Endocrinology,Doctor_281,20824,4403,17971,2853,2025-01-21,2025-01-23,2
2,B00003,A00003,P00003,Patient_3,15,Male,Dental,Doctor_105,6432,239,6228,204,2025-06-24,2025-07-03,9
3,B00004,A00004,P00004,Patient_4,50,Female,Pediatrics,Doctor_312,82670,9986,77817,4853,2025-07-23,2025-07-25,2
4,B00005,A00005,P00005,Patient_5,17,Female,Ophthalmology,Doctor_430,10376,4009,7571,2805,2025-04-06,2025-04-07,1

In [10]:
billing_master.to_csv(
    "../data/02_processed_data/billing_master.csv",
    index=False
)